### ISSUE TITLE
LDA topic name assignment doesn't work

### ISSUE THREAD

**Issue by lentil-soup** [davidatbu/openFraming#294]
https://drive.google.com/file/d/1lxM102gHQRZZtfUuiTmEkCE7zHdE8dJ8/view?usp=sharing

^ there's a video of the bug in action.

basically once you have a trained LDA model and you open that landing page, the next step would be to enter the names of the topics the model discovered. however, the first time you do that and click submit, nothing happens. if you then click on the button again, no matter how many labels you enter (regardless of whether it is the correct number of labels or not) you get a "you have the wrong number of labels" error message. 

This occurs on Chrome on macOS; not sure if this also occurs on other browser/OS combinations.

**Comment by lentil-soup** [comment]
I'm not concerned with error messages so much as the fact that you can't
download your results...

**Comment by davidatbu** [comment]
For documentation purposes, I'd like to leave a comment saying that, barring "other" bugs, this specific bug of not being able to download your results that @lentil-soup  mentoined in the comments was fixed.
