### ISSUE TITLE
(later on) change the backend, so it is not sensitive to the name of the column 

### ISSUE THREAD

**Issue by monajalal** [davidatbu/openFraming#312]
As long as the user has one or two columns and proper file extension, they should be good.

So they wouldn't get so many further errors just because they have wrong column names (making it easier for them to use their data without so much change).

**Comment by davidatbu** [comment]
Hi Mona, what if the user uploads the columns in the wrong order(first column is label, second column is example)?

I think it is better to be explicit about the requirements, rather than being implicit.

**Comment by monajalal** [comment]
Yeah I think you brought up a good point. Since it is more conventional to first have a sentence/data point and then its label, we can explicitly tell in the frontend as a written line.
