### ISSUE TITLE
write code to process and save the comma separated frames for a policy issue entered by a user in frontend and backend

### ISSUE THREAD

**Issue by monajalal** [davidatbu/openFraming#43]

**Comment by monajalal** [comment]
is it done, right @davidatbu ?

**Comment by davidatbu** [comment]
Hi @monajalal , the backend doens't need to do this as the JSON API specifies that it will receive a _list_, not a _string_. I believe @edward-edberg  did manage to split a string into a list in the frontend, but he should be the person to ask here.

**Comment by davidatbu** [comment]
Closing as this is self-evidently done because we can train classifiers using the frontend.
